### PR TITLE
Fixed infinite loop issue with Apnsp8 delivery

### LINKED ISSUE #606: Rpush::Daemon::Apnsp8::Delivery leaves notifications permanently in "processing"
**Describe the bug**
In `Rpush::Daemon::Apnsp8::Delivery#prepare_async_post`, when `@first_push` is `false`, it calls `#delayed_push_async`, which checks for `#streams_available?` , and loops until that is `true`. `#streams_available?` checks that `#remote_max_concurrent_streams` is greater than the current stream count. But, `#remote_max_concurrent_streams` has a branch that says, if `@client.remote_settings[:settings_max_concurrent_streams] == 0x7fffffff` then return `0`. And in that scenario, `#streams_available?` is always false, and it will loop forever, leaving the batch's notifications in "processing" permanently.

**To Reproduce**
Configure rpush to use `Apnsp8`. An instance of `Rpush::Daemon::Apnsp8::Delivery` will always process the first notification of batch, set the `@first_push` flag to `false`, and then leave all other notifications in the batch in "processing"

**Expected behavior**
It should process process all notifications. Should there be a reasonable default, like 100, in the case where `settings_max_concurrent_streams` is the default value?

**System configuration (please complete the following information):**
 - OS: macOS
 - OS version: 11.2.3
 - Ruby version: 2.4.5
 - Rails version: 4.2.11
 - Rpush version: 3.2.4 (But I've verified the same code exists on master)

**Additional context**
Thanks!

### PR DESCRIPTION
**Pull request by diminish7**
Fixes #606 

With Apnsp8 delivery, the second notification in a batch was always caught in an infinite loop, leaving it and all subsequent notification stuck in "processing"

### CODE REVIEW

File: lib/rpush/daemon/apnsp8/delivery.rb [hunk 1]
```diff
@@ -8,6 +8,7 @@ module Apnsp8
       class Delivery < Rpush::Daemon::Delivery
         RETRYABLE_CODES = [ 429, 500, 503 ]
         CLIENT_JOIN_TIMEOUT = 60
+        DEFAULT_MAX_CONCURRENT_STREAMS = 100
```
Comment (diminish7) [inline lib/rpush/daemon/apnsp8/delivery.rb:11]: Not sure what a reasonable default is, but this seemed like a good place to start. I guess we could also add a new config for it? Or alternatively, use the batch size config? Thoughts?

Comment (aried3r) [reply lib/rpush/daemon/apnsp8/delivery.rb:11]: Maybe @mariannegru can shed some light on where and how the `0x7fffffff` was supposed to work. As per the comment in the code, it does come from the `http-2` gem:
https://github.com/igrigorik/http-2/blob/v0.11.0/lib/http/2/connection.rb#L15

But there's also:
https://github.com/igrigorik/http-2/blob/v0.11.0/lib/http/2/connection.rb#L24

So maybe 100 is indeed the "correct" value here.

Comment (diminish7) [reply lib/rpush/daemon/apnsp8/delivery.rb:11]: The max current streams gets read from the server, but if the server doesn't provide that header, http2 uses `0x7fffffff` as the default, which is supposed to behave like "infinity".

That default of 100 in http2 is for the local settings vs the server settings. So that's another possible approach is to look at local settings if server settings have the default of `0x7fffffff`

Comment (aried3r) [reply lib/rpush/daemon/apnsp8/delivery.rb:11]: > That default of 100 in http2 is for the local settings vs the server settings.

Ah, thanks for clarifying, I missed that.

Just to clarify, if the http2 gem was configured to use "infinite" connections, we internally mapped that to 0 and this resulted in the bug. So I assume 100 being infinitely less than infinity but bigger than 0, this would be okay, but I have no deep knowledge of the inner workings of this gem.

> I guess we could also add a new config for it?

As for making it configurable, I have no opinion on this, since while we use http2 at work, we don't use the http2 gem directly. I assume being able to pass your own http2 client would be nice, since this is currently a private method, if I understood correctly.

https://github.com/rpush/rpush/blob/v5.4.0/lib/rpush/daemon/dispatcher/apns_http2.rb#L33-L41

A good first step is probably getting rid of this bug and if people feel the need to configure it, discuss it then and how we'd expose it.

> So that's another possible approach is to look at local settings if server settings have the default of 0x7fffffff

I assume that would again be `100` (or more specifically, the default local value of the http2 gem), since we don't let users of Rpush configure this value. Since the http2 client isn't configurable at all, using the default values of the http2 gem actually sounds reasonable.

Did I understand this correctly?

Comment (diminish7) [reply lib/rpush/daemon/apnsp8/delivery.rb:11]: > Did I understand this correctly?

Yep, that all sounds right to me!

> using the default values of the http2 gem actually sounds reasonable

So just to make sure I'm understanding, you're voting for the approach to check local settings if the server settings are set to `0x7fffffff`? Or are you saying, leave it hard-coded at 100, which matches the default local settings?

Comment (aried3r) [reply lib/rpush/daemon/apnsp8/delivery.rb:11]: > So just to make sure I'm understanding, you're voting for the approach to check local settings if the server settings are set to `0x7fffffff`? Or are you saying, leave it hard-coded at 100, which matches the default local settings?

Good point. I meant it as a question, kind of. If we can, I'd say let's use the local settings. That way we don't have to decide this ourselves but rather trust the http2-gems defaults. WDYT?

Comment (diminish7) [reply lib/rpush/daemon/apnsp8/delivery.rb:11]: Yep, I'm on board with that 👍  I'll play around with it later this afternoon.

Comment (diminish7) [reply lib/rpush/daemon/apnsp8/delivery.rb:11]: Oh oops, I take it back, it's a bit more complicated than that...  The `NetHttp2::Client` doesn't expose `#local_settings`. It wraps an `HTTP2::Client`, which has both `#remote_settings` and `#local_settings`, but the `NetHttp2::Client` only exposes `#remote_settings` for some reason. To get to `#local_settings`, we'd need to get a change pushed through on [net-http2](https://github.com/ostinelli/net-http2).

So I guess now I'm back to voting for the simple, hard-coded `100` approach.

What does everyone think?

Comment (aried3r) [reply lib/rpush/daemon/apnsp8/delivery.rb:11]: If we can't access the local settings, hard-coding to 100 with a comment that basically repeats your comment ("ideally we'd use `local_settings` but... so we use 100.") is good enough for now, as it fixes this infinite loop.

Comment (diminish7) [reply lib/rpush/daemon/apnsp8/delivery.rb:11]: Comment added, thanks!

**Review by aried3r — APPROVED** [review]

**Review by benlangfeld — APPROVED** [review]
